name: Netflix Movie Catalog Service Deployment

on:
  push:
    branches:
      - main

env:
  EC2_PUBLIC_IP: X.X.X.X  # TODO replace to your EC2 instance public IP

jobs:
  Deploy:
    name: Deploy in EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH to EC2 instance
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > mykey.pem
          chmod 400 mykey.pem
          scp -i mykey.pem -r . ubuntu@$EC2_PUBLIC_IP:~/
          ssh -i mykey.pem ubuntu@$EC2_PUBLIC_IP "bash deploy.sh"